#!/bin/bash
sudo yum install iptables-services -y
sudo systemctl enable iptables
sudo systemctl start iptables
sudo sysctl -w net.ipv4.ip_forward=1
sudo iptables -F
sudo /sbin/iptables -t nat -A POSTROUTING -o ens5 -j MASQUERADE
sudo service iptables save
