name: ci-infra-prd

on:
  pull_request:
    branches:
      - main
      - release/**
    paths:
      - .github/workflows/ci-infra-prd.yaml
      - docker/**
      - config/**
      - template/**
      - backend/**
      - '*.tf'

permissions:
  id-token: write
  contents: read

env:
  SERVICE: terraform-final-year
  ENVIRONMENT: prd
  REGION: ap-southeast-1

jobs:
  ci-infra-prd:
    runs-on: ubuntu-latest
    environment: prd

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.PRD_DEPLOY_ROLE }}
          aws-region: ${{ env.REGION }}

      - name: check assume role
        run: aws sts get-caller-identity
  
      - name: Run terraform init for backend
        run: |
          bash generate-config-file-dev.sh
          make plan 
  
      - name: Run terraform plan for infra
        run: make plan
      - name: Run terraform plan for infra
        run: make plan